# Generated by Django 3.2.14 on 2022-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlink',
            field=models.URLField(default='https://github.com/ginnto'),
        ),
    ]
